Sanity check to verify some modules are definately built

diff --git a/kernel/Makefile b/kernel/Makefile
--- a/kernel/Makefile
+++ b/kernel/Makefile
@@ -17,6 +17,25 @@ ${INSTALL_PATH}: linux/arch/x86_64/boot/bzImage
 	&& make install \
 		modules_install \
 		INSTALL_HDR_PATH=${PWD}/out headers_install
+	modules=""; \
+	for f in ahci bridge br_netfilter cdrom crc16 crypto_hash ehci_hcd \
+			ehci_pci ext4 iptable_nat ipt_MASQUERADE ipv6 isofs jbd2 libahci \
+			libata llc mbcache mii nf_conntrack nf_conntrack_ipv4 \
+			nf_defrag_ipv4 nf_nat nf_nat_ipv4 nf_nat_masquerade_ipv4 \
+			ohci_hcd ohci_pci overlay r8169 scsi_mod sd_mod sr_mod stp \
+			usb_common usbcore usbhid veth xhci_hcd xhci_pci xt_addrtype \
+			xt_conntrack \
+			binfmt_misc; do \
+			if [ -z "$$(grep "/$$f.ko" out/lib/modules/${KERNEL_VERSION}-grsec${LOCAL_VERSION}/modules.*)" ] \
+			&& [ -z "$$(grep "$(echo "/$$f.ko" | tr '-_' '_-')" out/lib/modules/${KERNEL_VERSION}-grsec${LOCAL_VERSION}/modules.*)" ] \
+				; then \
+				modules="$$modules $$f"; \
+		fi; \
+	done; \
+	if [ -n "$$modules" ]; then \
+		echo "Can't find:$$modules"; \
+		exit 1; \
+	fi
 	depmod -b ${INSTALL_PATH} ${KERNEL_VERSION}-grsec${LOCAL_VERSION}
 	cp linux/System.map ${INSTALL_PATH}
 	tar -C ${INSTALL_PATH} -cf out.tar lib System.map
